version: '3'

services:
  # PostgreSQL сервис
  postgres:
    image: postgres:latest
    container_name: mifi_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mifidatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend_network
    restart: unless-stopped

  # pgAdmin для управления PostgreSQL
  pgadmin:
    image: dpage/pgadmin4
    container_name: mifi_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8084:84"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./scripts/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - backend_network
    depends_on:
      - postgres
    restart: unless-stopped

  # Redis сервис
  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_network
    restart: unless-stopped

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
